### PR TITLE
This fixes the invalidContent function to support text fields

### PR DESCRIPTION
**Pull request by AnilRedshift**
Fix for https://github.com/qTip2/qTip2/issues/784

### CODE REVIEW

**Comment by AnilRedshift** [comment]
This is one case where I disagree with eslint. Parentheses here are for humans, not for the compiler. I know I'm in trouble if I have to go back to the spec to look up the correct order of operations. Just my opinion, but I've updated the code to pass the linter. Every workplace code guideline I've used has recommended parens when mixing && and || to be explicit about intent.

**Comment by IgorP120** [comment]
The underlying issue is actually a show-stopper: title is not displayed at all (!).
Can we please have this pull request merged to master sooner rather than later?

**Comment by AnilRedshift** [comment]
@Craga89 appears missing from this project as of recent.

**Comment by Craga89** [comment]
Better late than never guys! I'll be pushing a new release soon with this in

**Comment by Craga89** [comment]
Done. v3.0.3 is out :)

**Pull request merged**
